// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbfsjvn1_2gwlf4TsDz66JzyJqz9Jcfy0',
    appId: '1:25624893469:web:d75199878ed9eb82d50ef4',
    messagingSenderId: '25624893469',
    projectId: 'devfest-medango',
    authDomain: 'devfest-medango.firebaseapp.com',
    storageBucket: 'devfest-medango.firebasestorage.app',
    measurementId: 'G-X09RDPMMKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDhAEVbY0qjBVWb6nMvdQxadgGxS7UP66w',
    appId: '1:25624893469:android:d9ed26f3b558c582d50ef4',
    messagingSenderId: '25624893469',
    projectId: 'devfest-medango',
    storageBucket: 'devfest-medango.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7Yxh7FexmPasfM0da0Xl1Y0Mf7bIsFhQ',
    appId: '1:25624893469:ios:99e6671f02b888b6d50ef4',
    messagingSenderId: '25624893469',
    projectId: 'devfest-medango',
    storageBucket: 'devfest-medango.firebasestorage.app',
    iosClientId: '25624893469-omlkd530nabv4jqv35hi8blbfp2hi78j.apps.googleusercontent.com',
    iosBundleId: 'com.example.medanGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7Yxh7FexmPasfM0da0Xl1Y0Mf7bIsFhQ',
    appId: '1:25624893469:ios:99e6671f02b888b6d50ef4',
    messagingSenderId: '25624893469',
    projectId: 'devfest-medango',
    storageBucket: 'devfest-medango.firebasestorage.app',
    iosClientId: '25624893469-omlkd530nabv4jqv35hi8blbfp2hi78j.apps.googleusercontent.com',
    iosBundleId: 'com.example.medanGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbfsjvn1_2gwlf4TsDz66JzyJqz9Jcfy0',
    appId: '1:25624893469:web:97258a094af24a3ad50ef4',
    messagingSenderId: '25624893469',
    projectId: 'devfest-medango',
    authDomain: 'devfest-medango.firebaseapp.com',
    storageBucket: 'devfest-medango.firebasestorage.app',
    measurementId: 'G-HJ6Q2DDDH1',
  );
}
